# https://travis-ci.org/#!/smallnamespace/pymcts
sudo: false
language: python
python:
  - 3.5
cache: pip
install: pip install .[tests]
script: py.test
notifications:
  email:
    on_failure: always
    on_success: change
